sonar.projectKey=polis
sonar.projectName=POLIS
sonar.sourceEncoding=UTF-8

sonar.sources=cmd,internal,spec
sonar.exclusions=**/*_test.go
sonar.tests=cmd,internal,spec
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=.polis/coverage.out
